name: Staff Quick Test
on:
  push:
    branches: [ "develop", "main" ] # Agregamos ambas para estar seguros

jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo Staff
        run: echo "Pipeline funcionando"