name: Staff Quick Test
on:
  push:
    branches: [ "develop", "main" ] #se tenia que agregar la rama main para que pueda funcionar el pipeline

jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo Staff
        run: echo "Pipeline funcionando"